### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/RRTMGP.jl#174]
Documentation of the overall mathematical formulation is needed

**Comment by Venka97** [comment]
Hi @charleskawczynski ,

Thanks for this great repository. Would it be possible to complete the docs like [this](https://github.com/CliMA/RRTMGP.jl/blob/master/docs/src/RTE.md) one? It'll help a lot to understand what's going on.

**Comment by Venka97** [comment]
Thanks, I'll look through that. Sorry, I don't know much about RRTMGP, my background is in machine learning 🙂

**Comment by szy21** [comment]
Superseded by #325
