### ISSUE TITLE
Make docs strict

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/RRTMGP.jl#262]
Right now `strict = false` in `docs/make.jl`, which means that there are probably a lot of broken things in the docs. We should change this, as we have in ClimateMachine.jl, to `strict = true`

**Comment by charleskawczynski** [comment]
See #270

**Comment by sriharshakandala** [comment]
@charleskawczynski , @dennisYatunin ,
We have good documentation and code coverage. I believe this issue can be closed.

**Comment by charleskawczynski** [comment]
I prefer we leave this issue open until we make the docs strict.
