### ISSUE TITLE
Albedo Specification

### ISSUE THREAD

**Issue by jb-mackay** [CliMA/RRTMGP.jl#284]
We need to be able to set spatially varying albedo and pass this into the radiation calculation. Currently, radiation fluxes assume a single prescribed albedo value that cannot be changed externally.

**Comment by szy21** [comment]
It seems this has been addressed?

**Comment by jb-mackay** [comment]
I think so though I'm not sure exactly when or where, thanks for circling back @szy21. @LenkaNovak can you confirm this and close the issue, referencing the relevant PRs?

**Comment by szy21** [comment]
I think we can close it. Let me know if this issue hasn't been addressed.
