### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by szy21** [CliMA/RRTMGP.jl#325]
## Purpose
Clean up current documentation and add more documentation on equations and examples. Supersedes #262 #174 #112.

## People and Personnel
- Lead: @szy21 
- Collaborators:
- Reviewers: @tapios 

## Components
See Task Breakdown

## Inputs
N/A

## Results and deliverables
See Task Breakdown

## Task Breakdown And Tentative Due Date
- [x] Make docs strict and fix current breaking docs #326 1/27
- [x] #328 
- [x] #329
- [x] #331
- [x] #332
- [x] #333
- [x] #334
- [x] #342

## Proposed Delivery Date
(I will do this part-time, but can adjust the dates easily if it becomes a priority)

**Comment by tapios** [comment]
Looks great!

**Comment by bischtob** [comment]
@szy21, can we add a table for optical properties. There should be a separate table for each absorber species.

**Comment by szy21** [comment]
This is done and I'll close this issue.
