### ISSUE TITLE
Enable unthreaded launch option

### ISSUE THREAD

**Issue by szy21** [CliMA/RRTMGP.jl#335]

**Comment by szy21** [comment]
@sriharshakandala Should we close this?

**Comment by sriharshakandala** [comment]
Sure. Thanks.

**Comment by charleskawczynski** [comment]
Wait, why did we close this?

I’m going to reopen because thus is still an issue I’d like fixed since the threading doesn’t play well with flame graphs.

**Comment by simonbyrne** [comment]
Can't we just run Julia with a single thread if you want single profile info?

**Comment by charleskawczynski** [comment]
In theory yes. In practice, all of the threaded loops get dumped to the side in the flame graph: https://buildkite.com/clima/climaatmos-ci/builds/9533#0187e97c-019f-40b1-b589-ee6379e54ee6. From my experience, the width of flames at the top-level are not to be trusted. If this flame _is_ accurate then RRTMGP is a performance bottleneck contender (even if called only once every 10 steps).

**Comment by charleskawczynski** [comment]
Closed by #362
