### ISSUE TITLE
Update NCDatasets compats in environments

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/RRTMGP.jl#394]
See discussion in https://github.com/Alexander-Barth/NCDatasets.jl/issues/233

**Comment by charleskawczynski** [comment]
Wait, RRTMGP doesn't depend on NCDatasets

**Comment by charleskawczynski** [comment]
Ah, the test environment does. So we should update the compat there.

**Comment by Sbozzolo** [comment]
https://github.com/CliMA/RRTMGP.jl/commit/c135293d143559ec708448972550837b1e49f74e adds NCDatasets to RRTMGP.

The intent of this issue is to remind us that we should fix the issue at the root instead of pinning NCDatasets in RRTMGP (which indeed does not depend on NCDataset)

**Comment by charleskawczynski** [comment]
That doesn't add it to the package, only to the `test`, `gpuenv`, and `examples` environments

**Comment by charleskawczynski** [comment]
We shouldn't pin it in the root, then we'll need to add it as a direct dependency.

**Comment by charleskawczynski** [comment]
We can pin it in ClimaAtmos, that'll determine which version is used there anyway.

**Comment by Sbozzolo** [comment]
> That doesn't add it to the package, only to the `test`, `gpuenv`, and `examples` environments

You are right! I didn't pay enoguh attention

> We can pin it in ClimaAtmos, that'll determine which version is used there anyway.

https://github.com/CliMA/ClimaAtmos.jl/pull/2319

**Comment by charleskawczynski** [comment]
Let's keep this open (I've updated the title)
