### ISSUE TITLE
`RRTMGPI` callbacks fail on P100

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/RRTMGP.jl#400]
`RRTMGPI` callbacks, with `AllSkyRadiationWithClearSkyDiagnostics` option, are failing on the P100 GPUs with the following error:
```
ERROR: LoadError: CUDA error: device kernel image is invalid (code 200, ERROR_INVALID_IMAGE
```
The detailed error can be found here: https://buildkite.com/clima/climaatmos-ci/builds/15123#018c11f0-772b-47fc-9dd1-dc8e77e9a33d

The same simulation runs fine on the A100 GPUs. (e.g. here: https://buildkite.com/clima/climaatmos-target-gpu-simulations/builds/147#018c11f1-32a6-4573-921a-db600525bbba)

**Comment by simonbyrne** [comment]
I'm not sure. FYI here is what my tests had:
```
┌ Info: metadata size
│   flux = 160
│   flux_sw = 160
│   op = 120
│   bcs_sw = 144
│   src_sw = 392
│   nlay = 8
│   ncol = 8
│   major_gpt2bnd = 224
│   solar_src_scaled = 1792
│   as = 800
│   lookup_sw = 1320
└   lookup_sw_cld = 936
```

**Comment by simonbyrne** [comment]
what type of object is `solar_src_scaled`? why is it so large?

**Comment by sriharshakandala** [comment]
It's from the shortwave lookup table. It's the `relative solar source contribution from each `g-point``. https://github.com/CliMA/RRTMGP.jl/blob/main/src/optics/LookUpTables.jl#L725
But this is just a simple 1D device array.

**Comment by sriharshakandala** [comment]
Its a bit interesting. `major_gpt2bnd` and `solar_src_scaled` are both plain device arrays. My understanding is that for simple array, it just passes primarily a pointer and length. Not sure why this is metadata intensive. In fact, passing in arrays is generally recommended!

**Comment by simonbyrne** [comment]
Ah, those numbers weren't right. I needed to print `sizeof(typeof(...)))`
```
┌ Info: metadata size
│   flux = 160
│   flux_sw = 160
│   op = 120
│   bcs_sw = 144
│   src_sw = 392
│   nlay = 8
│   ncol = 8
│   major_gpt2bnd = 32
│   solar_src_scaled = 32
│   as = 800
│   lookup_sw = 1320
└   lookup_sw_cld = 936
```
