### ISSUE TITLE
`ClimaParams` is at the same time dependency and weak dependency of RRTMGP

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/RRTMGP.jl#512]
https://github.com/CliMA/RRTMGP.jl/blob/7d984ef02fa40e939e02b8650d2286f387029492/Project.toml#L10

should probably be removed?

**Comment by nefrathenrici** [comment]
https://github.com/CliMA/RRTMGP.jl/blob/7d984ef02fa40e939e02b8650d2286f387029492/src/RRTMGP.jl#L27-L29

This was intended to allow backwards compatibility with older Julia versions , but given that the minimum version is now 1.9, ClimaParams should just be a weakdep.
