### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/RRTMGP.jl#55]
Currently, the Julia implementation is a bit slow. Low hanging fruit for performance improvements are:

 - [ ] Add @inbounds to loops
 - [ ] Add [function barriers](https://docs.julialang.org/en/latest/manual/performance-tips/#kernel-functions-1)
 - [ ] Add type restrictions

**Comment by charleskawczynski** [comment]
#116 partially addresses this, but a systematic benchmark should be performed

**Comment by charleskawczynski** [comment]
#185 and #182 helped quite a bit with performance/memory management

**Comment by peterukk** [comment]
Have you profiled the code to see where the bottlenecks are? I'm curious to see if it's similar to Fortran. You might be interested to know that I have been working on optimizing the RRTMGP+RTE Fortran code, first by using neural networks to speed up the gas optics (big speed-up, accuracy seems OK but still needs a lot of testing), and more recently a general code revision - e.g. avoiding array transpositions by having g-points in the first dimension also in the solver (up to 40% speedup). So I think it's looking pretty good, but still needs a lot of work (e.g. shortwave code is currently broken).

What is the goal of this Julia port? Is it planned to be used in some dynamical model? I just found this, it sounds interesting!

**Comment by charleskawczynski** [comment]
Hi @peterukk! Yes, we have profiled the code a while back and did some things to improve performance. I suspect that RRTMGP.jl's performance is now roughly on par with the Fortran code, but we haven't really done a careful benchmark against the original code. This is on our to-do list. In terms of improving performance, aside from adding @inbounds (avoid safe indexing) and making sure that the code is type-stable, we implemented StaticArrays.jl (e.g., [here](https://github.com/climate-machine/RRTMGP.jl/blob/master/src/rrtmgp/GasOptics_kernels.jl#L244-L251)) in our interpolations to improve memory management and removed some array transposes (just as you did). We're definitely interested in the idea of using neural networks to speed up the gas optics (as our plan is to run on GPUs). Can you point me to where you're developing this?

In addition, we've made a lot of computations, and data structures, to be per-grid-point so that the functions are unaware of the spatial discretization. But this is more of a new feature.

Our ultimate goal is to use this code with our in-development climate model [CLIMA](https://github.com/climate-machine/CLIMA). You can read more about our team [here](https://clima.caltech.edu/).

**Comment by peterukk** [comment]
Very cool! The CLIMA project sounds tremendously exciting.

I am developing the code [here](https://github.com/peterukk/rte-rrtmgp/) (hasn't been updated in a while, will do so this week). The speed-up of the gas optics using neural networks, while still tangible, is less than I had hoped on CPU's. On GPU's, it should be very fast, so this is definitely relevant for your project. I will work on making an openACC/cublas kernel for it soon!

**Comment by charleskawczynski** [comment]
> Very cool! The CLIMA project sounds tremendously exciting.

It is :)

> I am developing the code here (hasn't been updated in a while, will do so this week).

Thanks for the link! I'm sure we may consider trying to develop a Julia version since we do intend to run on GPUs.

**Comment by peterukk** [comment]
Just remembered this - for your information the [RRTMGP-NN](https://github.com/peterukk/rte-rrtmgp-nn) package is much matured since last and [a paper has been published](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019MS001621). Besides demonstrating - I think - a successful NN emulation of RRTMGP,  it shows that refactoring RTE to be consistent with RRTMGP in its array structure was beneficial for performance. You might also want to know that the [shortwave solver can be made to work (fully) in single precision with a simple fix](https://github.com/earth-system-radiation/rte-rrtmgp/pull/39),  which is not currently in the main repo

**Comment by charleskawczynski** [comment]
@dennisYatunin, @sriharshakandala, have we done any rigorous performance benchmarks against the fortran RRTMGP? Maybe we can close this?

**Comment by sriharshakandala** [comment]
Our single thread performance is on par with the RRTMGP fortran code. We have reasonable performance. Additional optimization has been put on hold for now are there are other higher priority items. I believe we should be able to close this issue for now.

**Comment by szy21** [comment]
Based on the above comment I'm closing the issue for now.
